This is to do different types of correlation analysis.

In [6]:
from scipy import stats
import numpy as np

a = np.ones ((2,2))
b = np.ones ((2,2))
r = np.corrcoef(a,b)
print(a)
print(b)
print(r)
#stats.pearsonr(a, b)

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]
 [nan nan nan nan]]


/packages/7x/anaconda3/5.3.0/lib/python3.7/site-packages/numpy/lib/function_base.py:2530: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]


In [17]:
from scipy import stats
import numpy as np

a = [[1,2],[3,4]]
b = [[1,2],[3,4]]
print(a[0])
print(stats.pearsonr(a,b))
print(np.corrcoef(a,b))

[1, 2]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [56]:
from scipy import stats
import numpy as np
import csv
import pandas as pd

a = pd.read_csv("/home/mabbasi6/morphometry/correlation/data/3.csv", delimiter=',')
b = pd.read_csv("/home/mabbasi6/morphometry/correlation/data/3.csv", delimiter=',')

pandas.DataFrame.as_matrix
a
print(stats.pearsonr(a,b))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
with open('/home/mabbasi6/morphometry/correlation/data/3.csv') as csv3:
    csv_reader = csv.reader(csv_file, delimiter=',')
    line_count = 0
    for row in csv_reader:
        if line_count == 0:
            print(f'Column names are {", ".join(row)}')
            line_count += 1
        else:
            print(f'\t{row[0]} works in the {row[1]} department, and was born in {row[2]}.')
            line_count += 1
    print(f'Processed {line_count} lines.')

In [25]:
import SimpleITK as sitk
from scipy import stats

a = sitk.ReadImage("/home/mabbasi6/morphometry/correlation/raw/3/energy.mhd")
b = sitk.ReadImage("/home/mabbasi6/morphometry/correlation/raw/189/energy.mhd")
stats.pearsonr(a,b)

ModuleNotFoundError: No module named 'SimpleITK'

In [62]:
import csv

csv1 = open ('/home/mabbasi6/morphometry/correlation/new_ish/test1.csv', 'r')
csv2 = open ('/home/mabbasi6/morphometry/correlation/new_ish/test2.csv', 'r')
a = csv.reader (csv1)
b = csv.reader (csv2)

stats.pearsonr(float(a),float(b))

TypeError: float() argument must be a string or a number, not '_csv.reader'

In [94]:
import numpy as np
from scipy import stats

a = np.genfromtxt('/home/mabbasi6/morphometry/correlation/data/3.csv', delimiter=',', skip_header=1, usecols=range(1,2379))
b = np.genfromtxt('/home/mabbasi6/morphometry/correlation/data/189.csv', delimiter=',', skip_header=1, usecols=range(1,2379))
print(a)
#r = np.corrcoef(a,b)
#print(r)
print(stats.pearsonr(a,b))
#np.loadtxt(open("/home/mabbasi6/morphometry/correlation/new_ish/test1.csv", "rb"), delimiter=",", skiprows=0)

[[-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 ...
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [1]:
import numpy as np

a = np.genfromtxt('/home/mabbasi6/morphometry/correlation/new_ish/test2.csv', delimiter=',')
b = np.genfromtxt('/home/mabbasi6/morphometry/correlation/new_ish/test2.csv', delimiter=',')
#r = np.corrcoef(a,b)

print (a)
#print (r)

[nan nan]
