In [142]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%run nifti_tools.ipynb

In [143]:
ABA_mask = np.load('/data/bioprotean/ABA/MEMMAP/genes_list/ABA_mask_pos_std.npy')
ABA_mask.shape

(63113, 2941)

In [144]:
ABA_half = np.load('/data/bioprotean/ABA/MEMMAP/genes_list/genes_half_mask_pos_L2.npy')
ABA_half.shape

(31512, 2941)

In [145]:
gene0 = ABA_mask[:,0]

In [146]:
# Reconstructing the labels
indices_path = '/data/bioprotean/ABA/MEMMAP/genes_list/mask_indices.npy'

gene0_rc = reconstruct_ABA(gene0, indices_path, outside_value = -1, scale = False, mirror = False,\
    array_3D = True)

[-1.1144247  -1.1144247  -1.1144247  ... -0.7003571  -0.9378793
 -0.66122144]
(63113,)
(1, 63113)
[-1 -1 -1 ... -1 -1 -1]
[-1 -1 -1 ...  0  0  0]


In [159]:
gene0_rc[20,23,20]

0

ValueError: operands could not be broadcast together with shapes (159326,) (63113,) 

In [18]:
gene0_rc[50,20,25]

0

In [154]:
np.unique(np.load(indices_path)).shape

(63113,)

In [25]:
np.load(indices_path)

array([[  3259,   3260,   3261, ..., 156271, 156272, 156311]])

In [135]:
gene0_rc[gene0_rc == 0]

array([0, 0, 0, ..., 0, 0, 0])