In [1]:
import numpy as np

In [42]:
a = np.array([0,1,2,2,3,3,3])

In [24]:
values_vec = np.unique(a)
values_vec

array([0, 1, 2, 3])

In [25]:
rng = np.random.default_rng()
shuffled_values = rng.permutation(values_vec)
print(shuffled_values)

[2 1 0 3]


In [52]:
new_value = shuffled_values[3]
print(new_value)

3


In [53]:
old_value = values_vec[3]
old_value

3

In [54]:
change_vec = np.where(a==old_value, new_value, 0)
change_vec

array([0, 0, 0, 0, 3, 3, 3])

In [50]:
a

array([0, 1, 2, 2, 3, 3, 3])

In [20]:
def shuffle_vector(vector):
    '''
    Takes a vector of labels and randomly shuffles its values by shuffling for each value.
    For examples, all 0s are changed to 7. Not that every 0 gets a different value.
    
    Arguments:
        vector (vec): Vector to be shuffled
    
    Returns:
        shuffled_vec (vec): The shuffled vector
    '''
    
    # Taking a vector of different values in the input vector
    values_vec = np.unique(vector)
    
    # Creating a random Generator instance and shuffling the values
    rng = np.random.default_rng()
    shuffled_values = rng.permutation(values_vec)
    
    # Creating the vector to save the results
    shuffled_vec = np.zeros(vector.shape[0])
    
    # Looping over the unique values of the vector
    for count, old_value in enumerate(values_vec):
        
        # Creating a vector to change one value in all elements of the vector
        new_value = shuffled_values[count]
        change_vec = np.where(vector == old_value, new_value, 0)
        
        # Adding the changed vector to the storing vector
        shuffled_vec += change_vec
    
    return shuffled_vec

In [57]:
shuffle_vector(a)

array([2., 3., 0., 0., 1., 1., 1.])